/* =============================================================================
 * umbrella.js - the umbrella illustration (pure SVG, generated by code)
 *
 * umbrellaSVG(mode) returns an <svg> string. Each slide asks for a different
 * "mode" so the drawing matches the topic of the slide:
 *   ""        open umbrella with water flowing to the centre   (slide 4)
 *   "closed"  umbrella closed with the reverse mechanism       (slide 5)
 *   "tank"    handle cut-away with labelled parts              (slide 6)
 *   "bt"      phone + umbrella + battery module / USB-C        (slide 7)
 *   "haptic"  vibrating handle + "Find My" location pin        (slide 8)
 *
 * Gradients and clip paths (#gB, #gD, #gM, #cB ...) live in index.html.
 * The CSS animations (.fl, .pl, .wv, .rp, .vb ...) live in css/illustration.css.
 * ========================================================================== */

/** Point at fraction t (0..1) of the way from point a to point b. */
const lerp = (a, b, t) => [a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t];
/*
 * Geometry of the open canopy, seen from below (viewBox 0 0 620 460).
 *   HUB    - where all ribs meet (top of the shaft)
 *   CENTER - centre of the canopy opening
 *   RIM    - the 8 rib tips, placed on an ellipse around CENTER
 */
const HUB = [310, 92],
  CENTER = [310, 152],
  RIM = Array.from({ length: 8 }, (_, i) => {
    const t = (i * Math.PI) / 4;
    return [310 + 285 * Math.cos(t), 152 + 98 * Math.sin(t)].map((v) => +v.toFixed(1));
  });
// Outline of the canopy edge: a curve through the 8 rib tips, slightly concave between ribs.
let CANOPY_OUTLINE = "M" + RIM[0];
for (let i = 0; i < 8; i++) {
  const q = RIM[i],
    w = RIM[(i + 1) % 8],
    m = lerp(lerp(q, w, 0.5), CENTER, 0.035);
  CANOPY_OUTLINE += `Q${m} ${w}`;
}
CANOPY_OUTLINE += "Z";
/** Text label + leader line + dot pointing at a part of the drawing (slide 6). */
const calloutSVG = (x, y, t, an, lx, ly) =>
  `<path d="M${x} ${y}L${lx} ${ly}" stroke="#cfe3ff" stroke-width="1.2"/>
      <circle cx="${lx}" cy="${ly}" r="3" fill="#4da3ff"/>
      <text x="${x}" y="${y + 5}" font-size="16" fill="#cfe3ff" text-anchor="${an}" font-family="Inter,sans-serif">${t}</text>`;
/** Glass window with animated water level and a falling drop (inside the handle). `id` must be unique. */
const waterWindowSVG = (x, y, w, h, r, t) =>
  `<clipPath id="k${t}">
      <rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}"/>
      </clipPath>
      <rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="#05101f"/>
      <g clip-path="url(#k${t})">
      <g class="wl">
      <g transform="translate(0,${y + h * 0.45})">
      <path class="wv" d="M${x - 40} 0q6-4 12 0t12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0 12 0V${h}H${x - 40}Z" fill="#2b8cff" opacity=".85"/>
      </g>
      </g>
      <circle class="dp" cx="${x + w / 2}" cy="${y + 4}" r="2" fill="#bfe0ff"/>
      </g>
      <rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="none" stroke="#7b8392" stroke-width="1.5"/>
      <path d="M${x + 5} ${y + 5}V${y + h - 5}" stroke="#fff" opacity=".2" stroke-width="2"/>`;
/** Open canopy: outer fabric, blue interior, panels, ribs, stretchers and water-flow lines. */
const canopySVG = () => {
  let o = `<path d="${CANOPY_OUTLINE}" transform="translate(0,-16)" fill="url(#gD)" stroke="#4a4f5a" stroke-width="1.5"/>
      <path d="${CANOPY_OUTLINE}" fill="url(#gB)"/>
      <g clip-path="url(#cB)">`;
  RIM.forEach(
    (q, i) =>
      (o += `<path d="M${HUB}L${q}L${RIM[(i + 1) % 8]}Z" fill="${i % 2 ? "#000" : "#fff"}" opacity="${i % 2 ? 0.2 : 0.06}"/>`),
  );
  o += `<rect class="sh" x="-200" y="0" width="150" height="300" fill="url(#gSh)"/>
      </g>
      <path d="${CANOPY_OUTLINE}" fill="none" stroke="#0b1020" stroke-width="3.5"/>`;
  RIM.forEach((q) => {
    const c = lerp(HUB, q, 0.5);
    c[1] -= 6;
    o += `<path d="M${HUB}Q${c} ${q}" fill="none" stroke="#0a1020" stroke-width="5"/>
      <path d="M${HUB}Q${c} ${q}" fill="none" stroke="#7b8392" stroke-width="1.8"/>
      <circle cx="${q[0]}" cy="${q[1]}" r="2.6" fill="#5a606c"/>`;
  });
  RIM.forEach((q) => {
    const e = lerp(HUB, q, 0.55);
    o += `<path d="M310 130L${e}" stroke="#7b8392" stroke-width="1.4"/>`;
  });
  for (let i = 0; i < 8; i++) {
    const c = lerp(RIM[i], RIM[(i + 1) % 8], 0.5),
      x = lerp(HUB, c, 0.85),
      y = lerp(HUB, c, 0.22);
    o += `<path class="fl2" d="M${x}L${y}"/>
      <path class="fl" d="M${x}L${y}"/>`;
  }
  return o + `<ellipse cx="310" cy="92" rx="17" ry="9" fill="url(#gM)" stroke="#2a2e36"/>`;
};
/**
 * Shaft + funnel + silicone valve + grip (screen, power button, water window, thread).
 * mode "bt" shows battery cells inside the shaft; "haptic" shows the two vibration motors.
 */
const handleSVG = (m) => {
  let o = `<path d="M288 110H332L324 134H296Z" fill="url(#gM)" stroke="#2a2e36"/>
      <ellipse cx="310" cy="110" rx="22" ry="6" fill="#06142c" stroke="#aab0bb"/>
      <ellipse class="pl" cx="310" cy="110" rx="14" ry="3.5" fill="#52b9ff"/>
      <rect x="303" y="134" width="14" height="150" fill="url(#gM)"/>
      <rect x="307" y="134" width="6" height="150" fill="#04122a"/>`;
  // Slide 7: phone app (SmartUmbrella) sending data to the umbrella + lithium battery module and USB-C port.
  if (m == "bt")
    for (let k = 0; k < 4; k++)
      o += `<rect class="pl" style="animation-delay:-${k * 0.5}s" x="305.5" y="${148 + k * 32}" width="9" height="26" rx="2.5" fill="#dfe4ec"/>`;
  else
    o += `<path class="fl2" d="M310 138V280"/>
      <path class="fl" d="M310 138V280"/>`;
  [170, 215, 260].forEach(
    (y) => (o += `<rect x="300" y="${y}" width="20" height="4" rx="2" fill="url(#gM)"/>`),
  );
  o += `<rect x="302" y="262" width="16" height="20" rx="5" fill="#5aa0ff" opacity=".8" stroke="#cfe3ff"/>
      <path d="M305 270Q310 276 315 270" stroke="#0a2a66" fill="none" stroke-width="1.5"/>
      <rect x="293" y="283" width="34" height="11" rx="4" fill="url(#gM)" stroke="#2a2e36"/>`;
  o += `<g${m == "haptic" ? ' class="jt"' : ""}>
      <path d="M290 304Q290 294 300 294H320Q330 294 330 304L334 430Q334 448 318 448H302Q286 448 286 430Z" fill="url(#gG)" stroke="#3a3e48"/>
      <path d="M296 306L293 428" stroke="#fff" opacity=".13" stroke-width="3"/>`;
  o += `<rect class="pl" x="293" y="306" width="34" height="44" rx="10" fill="none" stroke="#4da3ff" stroke-width="2"/>
      <rect x="295" y="308" width="30" height="40" rx="9" fill="url(#gS)" stroke="#5a606c" stroke-width="2"/>
      <circle cx="305" cy="326" r="4" fill="#fff"/>
      <circle cx="311" cy="322" r="5.5" fill="#fff"/>
      <circle cx="317" cy="326" r="4" fill="#fff"/>
      <rect x="305" y="326" width="12" height="4" fill="#fff"/>
      <text x="310" y="338" font-size="7" fill="#fff" text-anchor="middle" font-family="Inter,sans-serif">22°C</text>
      <text x="310" y="346" font-size="6" fill="#dbe9ff" text-anchor="middle" font-family="Inter,sans-serif">70%</text>`;
  o += `<circle cx="310" cy="368" r="8" fill="#0d0e11" stroke="#5a606c"/>
      <path d="M306.5 365.5a5 5 0 1 0 7 0M310 362V368" stroke="#cfd5df" stroke-width="1.4" fill="none" stroke-linecap="round"/>`;
  o +=
    waterWindowSVG(298, 390, 24, 42, 6, "c" + (m || "o")) +
    `<rect x="292" y="436" width="36" height="12" rx="4" fill="none" stroke="#5a606c"/>
      <path d="M298 436l6 12M306 436l6 12M314 436l6 12M322 436l6 12" stroke="#6b7280"/>`;
  if (m == "haptic")
    o += `<circle class="pl" cx="299" cy="378" r="3.5" fill="#9aa3b2"/>
      <circle class="pl" cx="321" cy="378" r="3.5" fill="#9aa3b2"/>`;
  return o + `</g>`;
};
/** Full illustration for the given mode (see the list at the top of this file). */
const umbrellaSVG = (m = "") => {
  const wrapSVG = (vb, b) =>
    `<svg class="um rv" viewBox="${vb}" role="img" aria-label="Paraguas inteligente">${b}</svg>`;
  let o = "";
  // Slide 5: closed umbrella - the wet outer side folds inwards, the dry blue side stays outside.
  if (m == "closed") {
    o =
      handleSVG("") +
      `<path d="M268 52C256 120 282 200 304 262H316C338 200 364 120 352 52Z" fill="url(#gB)" stroke="#0b1020" stroke-width="2"/>`;
    [-2, -1, 0, 1, 2].forEach(
      (k) =>
        (o += `<path d="M${310 + k * 14} 56Q${310 + k * 25} 150 ${310 + k * 2.4} 260" fill="none" stroke="#0a1e4a" stroke-width="2.2"/>
      <path d="M${314 + k * 14} 56Q${314 + k * 25} 150 ${312 + k * 2.4} 260" fill="none" stroke="#5b92e8" opacity=".3"/>`),
    );
    o += `<path class="pl" d="M268 52C256 120 282 200 304 262H316C338 200 364 120 352 52Z" fill="none" stroke="#4da3ff" stroke-width="2"/>
      <ellipse cx="310" cy="52" rx="42" ry="11" fill="#0b0c10" stroke="#6b7280" stroke-width="2"/>
      <ellipse cx="310" cy="53" rx="33" ry="6.5" fill="url(#gD)"/>
      <rect x="270" y="150" width="80" height="14" rx="5" fill="#15181e" stroke="#4a4f5a"/>
      <rect x="302" y="152" width="16" height="10" rx="3" fill="url(#gM)"/>
      <path d="M304 262H316L313 274H307Z" fill="url(#gM)"/>`;
    return wrapSVG("0 0 620 460", o);
  }
  // Slide 6: handle cut-away (funnel -> hollow tube -> silicone valve -> water reservoir -> thread).
  if (m == "tank") {
    o = `<path d="M130 80Q310 -20 490 80L462 88Q310 20 158 88Z" fill="url(#gB)" stroke="#0b1020" stroke-width="2"/>
      <path class="fl2" d="M190 62L284 96M430 62L336 96"/>
      <path class="fl" d="M190 62L284 96M430 62L336 96"/>
      <path d="M246 70H374L340 120H280Z" fill="url(#gM)" stroke="#2a2e36" stroke-width="2"/>
      <ellipse cx="310" cy="70" rx="64" ry="10" fill="#06142c" stroke="#aab0bb" stroke-width="2"/>
      <ellipse class="pl" cx="310" cy="70" rx="40" ry="5" fill="#52b9ff"/>`;
    o += `<rect x="288" y="120" width="44" height="140" fill="url(#gM)" stroke="#2a2e36"/>
      <rect x="298" y="120" width="24" height="140" fill="#04122a"/>
      <path class="fl2" d="M310 126V250"/>
      <path class="fl" d="M310 126V250"/>
      <rect x="282" y="256" width="56" height="36" rx="10" fill="#5aa0ff" opacity=".8" stroke="#cfe3ff" stroke-width="2"/>
      <path d="M290 266Q310 284 330 266" stroke="#0a2a66" stroke-width="3" fill="none"/>`;
    o +=
      `<path d="M236 304Q236 292 250 292H370Q384 292 384 304L392 430Q392 452 368 452H252Q228 452 228 430Z" fill="url(#gG)" stroke="#3a3e48" stroke-width="2"/>` +
      waterWindowSVG(262, 316, 96, 100, 14, "ct") +
      `<rect x="246" y="424" width="128" height="26" rx="8" fill="#0d0e11" stroke="#5a606c" stroke-width="1.5"/>
      <path d="M256 424l12 26M276 424l12 26M296 424l12 26M316 424l12 26M336 424l12 26M356 424l12 26" stroke="#6b7280" stroke-width="2"/>`;
    o +=
      calloutSVG(276, 185, "Tubo central hueco", "end", 288, 185) +
      calloutSVG(274, 274, "Válvula unidireccional de silicona", "end", 282, 274) +
      calloutSVG(396, 366, "Depósito de agua en el mango", "start", 358, 366) +
      calloutSVG(396, 440, "Rosca inferior", "start", 374, 440);
    return wrapSVG("0 0 640 460", o);
  }
  if (m == "bt") {
    o = `<g transform="translate(168 60) scale(.7)">${canopySVG() + handleSVG("bt")}</g>
      <rect x="20" y="70" width="150" height="300" rx="26" fill="#0b0c10" stroke="#6b7280" stroke-width="3"/>
      <rect x="30" y="86" width="130" height="268" rx="16" fill="#0a1a3a"/>
      <text x="95" y="122" font-size="15" fill="#fff" text-anchor="middle" font-family="Chakra Petch,sans-serif">SmartUmbrella</text>
      <circle cx="78" cy="190" r="14" fill="#fff"/>
      <circle cx="98" cy="180" r="19" fill="#fff"/>
      <circle cx="118" cy="190" r="14" fill="#fff"/>
      <rect x="78" y="190" width="40" height="14" fill="#fff"/>
      <text x="95" y="256" font-size="34" fill="#fff" text-anchor="middle" font-family="Chakra Petch,sans-serif">22°C</text>
      <text x="95" y="290" font-size="14" fill="#cfe3ff" text-anchor="middle" font-family="Inter,sans-serif">Lluvia 70%</text>
      <rect x="50" y="312" width="90" height="22" rx="11" fill="#2468cc"/>`;
    o += `<path class="fl2" d="M176 240Q270 170 372 290"/>
      <path class="fl" d="M176 240Q270 170 372 290"/>`;
    for (let k = 0; k < 3; k++)
      o += `<circle class="rp" style="animation-delay:-${k}s" cx="385" cy="290" r="18" fill="none" stroke="#dfe4ec" stroke-width="2"/>`;
    o += `<rect x="610" y="60" width="70" height="250" rx="20" fill="#0d0e11" stroke="#8a93a3" stroke-width="3"/>`;
    for (let k = 0; k < 4; k++)
      o += `<rect class="pl" style="animation-delay:-${k * 0.5}s" x="624" y="${76 + k * 57}" width="42" height="46" rx="8" fill="#cfd5df"/>
      <rect x="638" y="${70 + k * 57}" width="14" height="6" rx="2" fill="#cfd5df"/>`;
    o += `<path class="fl2" d="M608 190L392 190"/>
      <path class="fl" d="M608 190L392 190"/>
      <rect x="600" y="338" width="90" height="30" rx="15" fill="#1b1f27" stroke="#9aa3b2" stroke-width="2"/>
      <rect x="612" y="347" width="66" height="12" rx="6" fill="#04122a"/>
      <path class="fl" d="M645 322V338"/>
      <text x="645" y="396" font-size="16" fill="#cfe3ff" text-anchor="middle" font-family="Inter,sans-serif">USB-C</text>
      <text x="645" y="30" font-size="16" fill="#cfe3ff" text-anchor="middle" font-family="Inter,sans-serif">5,000 mAh</text>`;
    return wrapSVG("0 0 720 460", o);
  }
  // Slides 4 and 8: open umbrella (slide 8 adds vibration waves and the "Find My" pin).
  o = canopySVG() + handleSVG(m);
  if (m == "haptic") {
    [
      [342, 320, 352, 340, 342, 360],
      [352, 310, 368, 340, 352, 370],
      [362, 300, 384, 340, 362, 380],
    ].forEach((a, i) => {
      o += `<path class="vb" style="animation-delay:${i * 0.2}s" d="M${a[0]} ${a[1]}Q${a[2]} ${a[3]} ${a[4]} ${a[5]}"/>
      <path class="vb" style="animation-delay:${i * 0.2}s" d="M${620 - a[0]} ${a[1]}Q${620 - a[2]} ${a[3]} ${620 - a[4]} ${a[5]}"/>`;
    });
    o += `<path d="M510 342c-14-18-22-28-22-40a22 22 0 0 1 44 0c0 12-8 22-22 40z" fill="#dfe4ec"/>
      <circle cx="510" cy="302" r="8" fill="#0b0c10"/>
      <ellipse class="rp" cx="510" cy="346" rx="28" ry="9" fill="none" stroke="#dfe4ec" stroke-width="2"/>
      <text x="510" y="384" font-size="16" fill="#cfe3ff" text-anchor="middle" font-family="Inter,sans-serif">Find My</text>`;
  }
  return wrapSVG("0 0 620 460", o);
};
